### ISSUE TITLE
Conflicting format restrictions for 'project_name'

### ISSUE THREAD

**Issue by jrobison153** [atomist-rugs/common-editors#5]
Looks like AddReadme.rug and PomParameterizer.rug specify conflicting restrictions on what the project can be named. AddReadme.rug specifies an @project_name parameter pattern 1 to 50 characters and PomParameterizer.rug specifies an @project_name parameter pattern 1 to 21 characters

So any project name greater than 21 characters but less than 50 will succeed when generating the README but fail during Pom generation. 

Probably need standardize on valid GitHub repository names and maybe just deal with the slack channel truncation, possibly issue a warning to the user if they exceed 21 characters.

**Comment by jrobison153** [comment]
One other thing to note, I ran into this issue using the [rug-archive](https://github.com/atomist-rugs/rug-archive) generator. This issue may not be obvious until both of these editors are composed together by another editor/generator

**Comment by kipz** [comment]
Thanks for the bug report @jrobison153.

atomist-rugs:common-editors:0.5.1 fixes the issue by removing maxLength restrictions from both editors.
